[2021-06-06 17:50:20,422] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: forex_data_pipeline.spark 2021-06-05T00:00:00+00:00 [queued]>
[2021-06-06 17:50:20,527] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: forex_data_pipeline.spark 2021-06-05T00:00:00+00:00 [queued]>
[2021-06-06 17:50:20,530] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-06-06 17:50:20,533] {taskinstance.py:1043} INFO - Starting attempt 6 of 7
[2021-06-06 17:50:20,536] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-06-06 17:50:20,572] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): spark> on 2021-06-05T00:00:00+00:00
[2021-06-06 17:50:20,603] {standard_task_runner.py:52} INFO - Started process 3570 to run task
[2021-06-06 17:50:20,614] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'forex_data_pipeline', 'spark', '2021-06-05T00:00:00+00:00', '--job-id', '54', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag_spark.py', '--cfg-path', '/tmp/tmp7729w2wx', '--error-file', '/tmp/tmpa3bmofxn']
[2021-06-06 17:50:20,620] {standard_task_runner.py:77} INFO - Job 54: Subtask spark
[2021-06-06 17:50:20,759] {logging_mixin.py:104} INFO - Running <TaskInstance: forex_data_pipeline.spark 2021-06-05T00:00:00+00:00 [running]> on host 72eec67484fb
[2021-06-06 17:50:20,889] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=admin@localhost.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=forex_data_pipeline
AIRFLOW_CTX_TASK_ID=spark
AIRFLOW_CTX_EXECUTION_DATE=2021-06-05T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-06-05T00:00:00+00:00
[2021-06-06 17:50:20,895] {logging_mixin.py:104} INFO - ÉNTRO AQUI!!!???¿
[2021-06-06 17:51:35,448] {logging_mixin.py:104} INFO - ESTOY
[2021-06-06 17:59:32,467] {local_task_job.py:77} ERROR - Received SIGTERM. Terminating subprocesses
[2021-06-06 17:59:34,397] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 3570
[2021-06-06 17:59:36,556] {taskinstance.py:1239} ERROR - Received SIGTERM. Terminating subprocesses.
[2021-06-06 17:59:38,913] {java_gateway.py:1210} INFO - Error while receiving.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/java_gateway.py", line 1200, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1241, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2021-06-06 17:59:47,149] {java_gateway.py:1051} ERROR - Exception while sending command.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/java_gateway.py", line 1200, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1241, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/java_gateway.py", line 1033, in send_command
    response = connection.send_command(command)
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/java_gateway.py", line 1212, in send_command
    "Error while receiving", e, proto.ERROR_ON_RECEIVE)
py4j.protocol.Py4JNetworkError: Error while receiving
